### ISSUE TITLE
bat2exe compiler link is dead

### ISSUE THREAD

**Issue by Highview-Lucas** [hiiamok/png2ImageMagickICO#1]
bat2exe compiler linked in the readme is a dead link

someone has mirrored the project here: https://github.com/tokyoneon/B2E

**Comment by hiiamok** [comment]
Thanks for the info @Highview-Lucas 
gonna update the readme

**Comment by hiiamok** [comment]
fixed in https://github.com/hiiamok/png2ImageMagickICO/commit/c120e8b2be085224d3e30fe214b99352d5044391
